# Generated by Django 5.2.7 on 2025-10-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('release_date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Czas trwania w minutach')),
                ('directors', models.CharField(blank=True, max_length=255)),
                ('poster_path', models.CharField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
            options={
                'ordering': ['-release_date', 'title'],
            },
        ),
    ]
