# Generated by Django 5.2.7 on 2025-11-18 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_is_special_event_alter_movie_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cinema_release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
