# Generated by Django 5.2.7 on 2025-11-20 14:52

from django.db import migrations, models
from django.db.models import F


def fix_cinema_release_date(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    # Ustaw cinema_release_date = release_date tam gdzie narusza przyszły constraint
    violating = Movie.objects.filter(release_date__gt=F('cinema_release_date'))
    for m in violating.iterator():
        m.cinema_release_date = m.release_date
        # Minimalny zapis tylko tego pola
        m.save(update_fields=['cinema_release_date'])



class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_cinema_release_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-cinema_release_date', 'title']},
        ),
        migrations.AlterField(
            model_name='movie',
            name='cinema_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(fix_cinema_release_date, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='movie',
            constraint=models.CheckConstraint(condition=models.Q(('release_date__lte', models.F('cinema_release_date'))), name='release_date_lte_cinema_release_date'),
        ),
    ]
