# Generated by Django 5.2.7 on 2025-11-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_options_alter_movie_cinema_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cinema_release_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='movie',
            name='directors',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.CharField(),
        ),
    ]
