# Generated by Django 5.2.7 on 2025-11-24 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='seat_type',
        ),
        migrations.DeleteModel(
            name='SeatType',
        ),
    ]
