# Generated by Django 5.2.7 on 2025-11-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0002_remove_seat_seat_type_delete_seattype'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='row_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('auditorium', 'row_number', 'seat_number'), name='uniq_seat_per_auditorium_row_number'),
        ),
    ]
