# Generated by Django 5.2.7 on 2025-11-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0003_alter_seat_unique_together_alter_seat_row_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_number',
            field=models.IntegerField(),
        ),
    ]
