# Generated by Django 5.2.8 on 2025-11-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0004_screening_chk_start_time_gte_published_at_and_more'),
        ('tickets', '0002_tickettype_ticket_order_number_ticket_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_tickets', models.IntegerField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('time_from', models.TimeField(blank=True, null=True)),
                ('time_to', models.TimeField(blank=True, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('screening', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screenings.screening')),
                ('ticket_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.tickettype')),
            ],
        ),
    ]
