# Generated by Django 5.2.8 on 2025-11-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_promotionrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
