# Generated by Django 5.2.7 on 2025-12-08 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_email_ticket_first_name_ticket_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='order_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
