# Generated by Django 5.2.8 on 2025-12-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PAID', max_length=10),
        ),
    ]
