# Generated by Django 5.2.7 on 2025-11-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditorium', '0001_initial'),
        ('movies', '0002_movie_is_special_event_alter_movie_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorium.auditorium')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('start_time', 'auditorium'), name='unique_auditorium_start_time')],
            },
        ),
    ]
