# Generated by Django 5.2.7 on 2025-11-05 17:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='2D', max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='screening',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screening',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='screening',
            name='projection_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='screenings.projectiontype'),
        ),
    ]
