# Generated by Django 5.2.7 on 2025-11-15 16:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0002_projectiontype_screening_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screening',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
